#!/bin/bash -x

#git checkout master

# Creating the new tag
new_tag="$1"
#git tag $new_tag

# Setting the version on the front end
pushd ../../ui/
node set_version.js
#git add src/version.ts
popd

# Changing the docker-compose prod
sed -i "s/dessalines\/lemmy:.*/dessalines\/lemmy:$new_tag/" ../prod/docker-compose.yml
#git add ../prod/docker-compose.yml

# The commit
#git commit -m"Upping version."

#git push origin $new_tag
#git push

# Rebuilding docker
docker-compose build
docker tag dev_lemmy:latest shtripok/lemmy:x64-$new_tag
docker push shtripok/lemmy:x64-$new_tag

# Build for Raspberry Pi armv7hf
docker build -t lemmy:armv7hf -f Dockerfile.armv7hf ../../
docker tag lemmy:armv7hf shtripok/lemmy:armv7hf-$new_tag
docker push shtripok/lemmy:armv7hf-$new_tag


docker build -t lemmy:aarch64 -f Dockerfile.aarch64 ../../
docker tag lemmy:aarch64 shtripok/lemmy:arm64-$new_tag
docker push shtripok/lemmy:arm-$new_tag

docker manifest create shtripok/lemmy:latest \
    shtripok/lemmy:armv7hf-$new_tag \
    shtripok/lemmy:x64-$new_tag \
    shtripok/lemmy:arm64-$new_tag


#docker manifest create shtripok/pictshare:latest \
#shtripok/pictshare:armv7 \
#shtripok/pictshare:x64 \
#shtripok/pictshare:arm64

docker manifest push shtripok/pictshare:latest

# Rebuilding the docker nocross
# pushd ../nocross
# docker-compose build
# docker tag nocross_lemmy:latest dessalines/lemmy:nocross-$new_tag
# docker push dessalines/lemmy:$new_tag
# popd

# Pushing to any ansible deploys
#cd ../../ansible
#ansible-playbook lemmy.yml --become
