# TODO: The when: platform conditionals aren't working currently
# See https://github.com/woodpecker-ci/woodpecker/issues/1677

variables:
  - &rust_image "rust:1.75"
  - &install_pnpm "corepack enable pnpm"
  - &slow_check_paths
    - path:
        # rust source code
        - "crates/**"
        - "src/**"
        - "**/Cargo.toml"
        - "Cargo.lock"
        # database migrations
        - "migrations/**"
        # typescript tests
        - "api_tests/**"
        # config files and scripts used by ci
        - ".woodpecker.yml"
        - ".rustfmt.toml"
        - "scripts/update_config_defaults.sh"
        - "diesel.toml"
        - ".gitmodules"

# Broken for cron jobs currently, see
# https://github.com/woodpecker-ci/woodpecker/issues/1716
# clone:
#   git:
#     image: woodpeckerci/plugin-git
#     settings:
#       recursive: true
#       submodule_update_remote: true

steps:
  prepare_repo:
    image: alpine:3
    commands:
      - ldconfig -p
      - apk add git
      - git submodule init
      - git submodule update

  prettier_check:
    image: tmknom/prettier:3.0.0
    commands:
      - prettier -c . '!**/volumes' '!**/dist' '!target' '!**/translations' '!api_tests/pnpm-lock.yaml'

  toml_fmt:
    image: tamasfe/taplo:0.8.1
    commands:
      - taplo format --check

  sql_fmt:
    image: backplane/pgformatter:latest
    commands:
      - ./scripts/sql_format_check.sh

  cargo_fmt:
    image: rustlang/rust:nightly
    environment:
      # store cargo data in repo folder so that it gets cached between steps
      CARGO_HOME: .cargo_home
    commands:
      # need make existing toolchain available
      - cargo +nightly fmt -- --check

  cargo_machete:
    image: rustlang/rust:nightly
    commands:
      - wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
      - tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
      - cp cargo-binstall /usr/local/cargo/bin
      - cargo binstall -y cargo-machete
      - cargo machete

  ignored_files:
    image: alpine:3
    commands:
      - apk add git
      - IGNORED=$(git ls-files --cached -i --exclude-standard)
      - if [[ "$IGNORED" ]]; then echo "Ignored files present:\n$IGNORED\n"; exit 1; fi

  # make sure api builds with default features (used by other crates relying on lemmy api)
  check_api_common_default_features:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - cargo check --package lemmy_api_common
    when: *slow_check_paths

  lemmy_api_common_doesnt_depend_on_diesel:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - "! cargo tree -p lemmy_api_common --no-default-features -i diesel"
    when: *slow_check_paths

  lemmy_api_common_works_with_wasm:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - "rustup target add wasm32-unknown-unknown"
      - "cargo check --target wasm32-unknown-unknown -p lemmy_api_common"
    when: *slow_check_paths

  check_defaults_hjson_updated:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - export LEMMY_CONFIG_LOCATION=./config/config.hjson
      - ./scripts/update_config_defaults.sh config/defaults_current.hjson
      - diff config/defaults.hjson config/defaults_current.hjson
    when: *slow_check_paths

  check_diesel_schema:
    image: willsquire/diesel-cli
    environment:
      CARGO_HOME: .cargo_home
      DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
    commands:
      - diesel migration run
      - diesel print-schema --config-file=diesel.toml > tmp.schema
      - diff tmp.schema crates/db_schema/src/schema.rs
    when: *slow_check_paths

  check_db_perf_tool:
    image: *rust_image
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      RUST_BACKTRACE: "1"
      CARGO_HOME: .cargo_home
    commands:
      # same as scripts/db_perf.sh but without creating a new database server
      - export LEMMY_CONFIG_LOCATION=config/config.hjson
      - cargo run --package lemmy_db_perf -- --posts 10 --read-post-pages 1
    when: *slow_check_paths

  cargo_clippy:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets --features console -- -D warnings
    when: *slow_check_paths

  cargo_build:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - cargo build
      - mv target/debug/lemmy_server target/lemmy_server
      - ldd target/lemmy_server
    when: *slow_check_paths

  check_diesel_migration_revertable:
    image: willsquire/diesel-cli
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      RUST_BACKTRACE: "1"
      CARGO_HOME: .cargo_home
      DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      PGUSER: lemmy
      PGPASSWORD: password
      PGHOST: database
      PGDATABASE: lemmy
    commands:
      - diesel migration run
      # Make sure that the migration works both with and without the `r` schema
      - diesel migration redo
      # Run schema setup twice, which fails on the 2nd time if `DROP SCHEMA IF EXISTS r CASCADE` drops the wrong things
      - target/lemmy_server --disable-scheduled-tasks --disable-http-server --disable-activity-sending
      - target/lemmy_server --disable-scheduled-tasks --disable-http-server --disable-activity-sending
      - diesel migration redo
    when: *slow_check_paths

  cargo_test:
    image: *rust_image
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      RUST_BACKTRACE: "1"
      CARGO_HOME: .cargo_home
    commands:
      - export LEMMY_CONFIG_LOCATION=../../config/config.hjson
      - cargo test --workspace --no-fail-fast
    when: *slow_check_paths

  run_federation_tests:
    image: node:20-bookworm-slim
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432
      DO_WRITE_HOSTS_FILE: "1"
    commands:
      - *install_pnpm
      - apt update && apt install -y bash curl postgresql-client
      - bash api_tests/prepare-drone-federation-test.sh
      - cd api_tests/
      - pnpm i
      - pnpm api-test
    when: *slow_check_paths

  federation_tests_server_output:
    image: alpine:3
    commands:
      # `|| true` prevents this step from appearing to fail if the server output files don't exist
      - cat target/log/lemmy_*.out || true
      - "# If you can't see all output, then use the download button"
    when:
      status: [failure]

  publish_release_docker:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: dessalines/lemmy
      dockerfile: docker/Dockerfile
      platforms: linux/amd64, linux/arm64
      build_args:
        - RUST_RELEASE_MODE=release
      tag: ${CI_COMMIT_TAG}
    when:
      event: tag

  nightly_build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: dessalines/lemmy
      dockerfile: docker/Dockerfile
      platforms: linux/amd64,linux/arm64
      build_args:
        - RUST_RELEASE_MODE=release
      tag: dev
    when:
      event: cron

  # using https://github.com/pksunkara/cargo-workspaces
  publish_to_crates_io:
    image: *rust_image
    commands:
      - 'echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs"'
      - cargo install cargo-workspaces
      - cp -r migrations crates/db_schema/
      - cargo login "$CARGO_API_TOKEN"
      - cargo workspaces publish --from-git --allow-dirty --no-verify --allow-branch "${CI_COMMIT_TAG}" --yes custom "${CI_COMMIT_TAG}"
    secrets: [cargo_api_token]
    when:
      event: tag

  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Lemmy CI build failed: ${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'lemmy:${CI_COMMIT_TAG} deployed' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lemmy
      POSTGRES_PASSWORD: password
