# TODO: The when: platform conditionals aren't working currently
# See https://github.com/woodpecker-ci/woodpecker/issues/1677

variables:
  # When updating the rust version here, be sure to update versions in `docker/Dockerfile`
  # as well. Otherwise release builds can fail if Lemmy or dependencies rely on new Rust
  # features. In particular the ARM builder image needs to be updated manually in the repo below:
  # https://github.com/raskyld/lemmy-cross-toolchains
  - &rust_image "rust:1.81"
  - &rust_nightly_image "rustlang/rust:nightly"
  - &install_pnpm "npm install -g corepack@latest && corepack enable pnpm"
  - &install_binstall "wget -q -O- https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -xvz -C /usr/local/cargo/bin"
  - &slow_check_paths
    - event: pull_request
      path:
        include: [
            # rust source code
            "crates/**",
            "src/**",
            "**/Cargo.toml",
            "Cargo.lock",
            # database migrations
            "migrations/**",
            # typescript tests
            "api_tests/**",
            # config files and scripts used by ci
            ".woodpecker.yml",
            ".rustfmt.toml",
            "scripts/update_config_defaults.sh",
            "diesel.toml",
            ".gitmodules",
          ]

steps:
  prepare_repo:
    image: alpine:3
    commands:
      - apk add git
      - git submodule init
      - git submodule update
    when:
      - event: [pull_request, tag]

  prettier_check:
    image: tmknom/prettier:3.4.2
    commands:
      - prettier -c . '!**/volumes' '!**/dist' '!target' '!**/translations' '!api_tests/pnpm-lock.yaml'
    when:
      - event: pull_request

  toml_fmt:
    image: tamasfe/taplo:0.9.3
    commands:
      - taplo format --check
    when:
      - event: pull_request

  sql_fmt:
    image: *rust_image
    commands:
      - apt-get install perl make bash
      - ./scripts/alpine_install_pg_formatter.sh
      - ./scripts/sql_format_check.sh
    when:
      - event: pull_request

  cargo_fmt:
    image: *rust_nightly_image
    environment:
      # store cargo data in repo folder so that it gets cached between steps
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - rustup component add rustfmt --toolchain nightly
      - cargo +nightly fmt -- --check
    when:
      - event: pull_request

  cargo_shear:
    image: *rust_nightly_image
    commands:
      - *install_binstall
      - cargo binstall -y cargo-shear
      - cargo shear
    when:
      - event: pull_request

  ignored_files:
    image: alpine:3
    commands:
      - apk add git
      - IGNORED=$(git ls-files --cached -i --exclude-standard)
      - if [[ "$IGNORED" ]]; then echo "Ignored files present:\n$IGNORED\n"; exit 1; fi
    when:
      - event: pull_request

  no_empty_files:
    image: alpine:3
    commands:
      # Makes sure there are no files smaller than 2 bytes
      # Don't use completely empty, as some editors use newlines
      - EMPTY_FILES=$(find crates migrations api_tests/src config -type f -size -2c)
      - if [[ "$EMPTY_FILES" ]]; then echo "Empty files present:\n$EMPTY_FILES\n"; exit 1; fi
    when:
      - event: pull_request

  cargo_clippy:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets -- -D warnings
    when: *slow_check_paths

  # `DROP OWNED` doesn't work for default user
  create_database_user:
    image: postgres:16-alpine
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGDATABASE: lemmy
    commands:
      - psql -c "CREATE USER lemmy WITH PASSWORD 'password' SUPERUSER;"
    when: *slow_check_paths

  cargo_test:
    image: *rust_image
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      RUST_BACKTRACE: "1"
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
      LEMMY_TEST_FAST_FEDERATION: "1"
      LEMMY_CONFIG_LOCATION: /woodpecker/src/github.com/LemmyNet/lemmy/config/config.hjson
    commands:
      # Install pg_dump for the schema setup test (must match server version)
      - apt update && apt install -y lsb-release
      - sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - apt update && apt install -y postgresql-client-16
      # Run tests
      - cargo test --workspace --no-fail-fast
    when: *slow_check_paths

  # make sure api builds with default features (used by other crates relying on lemmy api)
  check_api_common_default_features:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - cargo check --package lemmy_api_common
    when: *slow_check_paths

  lemmy_api_common_doesnt_depend_on_diesel:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - "! cargo tree -p lemmy_api_common --no-default-features -i diesel"
    when: *slow_check_paths

  lemmy_api_common_works_with_wasm:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - "rustup target add wasm32-unknown-unknown"
      - "cargo check --target wasm32-unknown-unknown -p lemmy_api_common"
    when: *slow_check_paths

  check_defaults_hjson_updated:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - ./scripts/update_config_defaults.sh config/defaults_current.hjson
      - diff config/defaults.hjson config/defaults_current.hjson
    when: *slow_check_paths

  cargo_build:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - cargo build
      - mv target/debug/lemmy_server target/lemmy_server
    when: *slow_check_paths

  check_diesel_schema:
    image: *rust_image
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      RUST_BACKTRACE: "1"
      CARGO_HOME: .cargo_home
      RUSTUP_HOME: .rustup_home
    commands:
      - *install_binstall
      - cp crates/db_schema_file/src/schema.rs tmp.schema
      - target/lemmy_server migration --all run
      - apt-get update && apt-get install -y postgresql-client
      # diesel_cli@2.2.8 is the last version that supports rust 1.81, which we are currently locked on due to perf regressions on rust 1.82+ :(
      - cargo binstall --locked diesel_cli@2.2.8 -y
      - export PATH="$CARGO_HOME/bin:$PATH"
      - diesel print-schema
      - diff tmp.schema crates/db_schema_file/src/schema.rs
    when: *slow_check_paths

  run_federation_tests:
    image: node:22-bookworm-slim
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432
      DO_WRITE_HOSTS_FILE: "1"
    commands:
      - *install_pnpm
      - apt-get update && apt-get install -y bash curl postgresql-client
      - bash api_tests/prepare-drone-federation-test.sh
      - cd api_tests/
      - pnpm i
      - pnpm api-test
    when: *slow_check_paths

  federation_tests_server_output:
    image: alpine:3
    commands:
      # `|| true` prevents this step from appearing to fail if the server output files don't exist
      - cat target/log/lemmy_*.out || true
      - "# If you can't see all output, then use the download button"
    when:
      - event: pull_request
        status: failure

  publish_release_docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: dessalines/lemmy
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms: linux/amd64, linux/arm64
      build_args:
        RUST_RELEASE_MODE: release
      tag: ${CI_COMMIT_TAG}
    when:
      - event: tag

  # lemmy container doesnt run as root so we need to change permissions to let it copy the binary
  chmod_for_native_binary:
    image: alpine:3
    commands:
      - chmod 777 .
    when:
      - event: tag

  # extract lemmy binary from newly built docker image into workspace folder
  extract_native_binary:
    image: dessalines/lemmy:${CI_COMMIT_TAG=default}
    commands:
      - cp /usr/local/bin/lemmy_server .
    when:
      - event: tag

  prepare_native_binary:
    image: alpine:3
    commands:
      - sha256sum lemmy_server > sha256sum.txt
      - gzip lemmy_server
    when:
      - event: tag

  # https://woodpecker-ci.org/plugins/Release
  publish_native_binary:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - lemmy_server.gz
        - sha256sum.txt
      title: ${CI_COMMIT_TAG}
      prerelease: true
      api-key:
        from_secret: github_token
    when:
      - event: tag

  # using https://github.com/pksunkara/cargo-workspaces
  publish_to_crates_io:
    image: *rust_image
    environment:
      CARGO_API_TOKEN:
        from_secret: cargo_api_token
    commands:
      - *install_binstall
      # Install cargo-workspaces, need pinned version for Rust 1.81 compat
      - cargo binstall -y cargo-workspaces@0.3.6
      - cp -r migrations crates/db_schema/
      - cargo workspaces publish --token "$CARGO_API_TOKEN" --from-git --allow-dirty --no-verify --allow-branch "${CI_COMMIT_TAG}" --yes custom "${CI_COMMIT_TAG}"
    when:
      - event: tag

  notify_success:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ✔️ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [success]

  notify_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ❌ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ${CI_REPO_NAME}:${CI_COMMIT_TAG} deployed' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag

services:
  database:
    # 15-alpine image necessary because of diesel tests
    image: pgautoupgrade/pgautoupgrade:15-alpine
    environment:
      POSTGRES_DB: lemmy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
