#!/bin/bash
set -e

cargo +nightly fmt

cargo +nightly clippy --workspace --tests --all-targets --all-features -- \
    -D warnings -D deprecated -D clippy::perf -D clippy::complexity -D clippy::dbg_macro

./scripts/update_config_defaults.sh
git add config/defaults.hjson
