name: "\U0001F680 Feature request"
description: Suggest an idea for improving Lemmy
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have a suggestion about Lemmy's UI?
        For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a bug report please do the following.
      options:
        - label: Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
          required: true
        - label: Did you check to see if this issue already exists?
          required: true
        - label: Is this only a feature request? Do not put multiple feature requests in one issue.
          required: true
        - label: Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your proposal related to a problem?
      description: |
        Provide a clear and concise description of what the problem is.
        For example, "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: |
        Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: |
        Let us know about other solutions you've tried or researched.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Is there anything else you can add about the proposal?
        You might want to link to related issues here, if you haven't already.
