name: "? Question"
description: General questions about Lemmy
title: "Question: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a support request or discussion?
        Use https://lemmy.ml/c/lemmy_support

        Have a question about how Lemmy works?
        Please check the docs first: https://join-lemmy.org/docs/en/index.html
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's the question you have about Lemmy?
    validations:
      required: true
