[package]
name = "lemmy_api_routes"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []

[dependencies]
lemmy_api = { workspace = true }
lemmy_api_crud = { workspace = true }
lemmy_utils = { workspace = true }
lemmy_routes = { workspace = true }
actix-web = { workspace = true }
