[package]
name = "lemmy_db_views_api_misc"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = [
  "lemmy_db_schema/full",
  "lemmy_db_views_post/full",
  "extism",
  "extism-convert",
]
ts-rs = ["dep:ts-rs", "lemmy_db_views_post/ts-rs"]

[dependencies]
lemmy_db_schema.workspace = true
lemmy_db_views_post.workspace = true
serde.workspace = true
serde_with.workspace = true
url.workspace = true
ts-rs = { workspace = true, optional = true }
extism = { workspace = true, optional = true }
extism-convert = { workspace = true, optional = true }
