[package]
name = "lemmy_proc_macros"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[lib]
name = "lemmy_proc_macros"
path = "src/lib.rs"
doctest = false
proc_macro = true

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full"] }
