when:
  event: cron

platform: linux/amd64

steps:
  prepare_repo:
    image: alpine:3
    commands:
      - apk add git
        #- git fetch --tags
      - git submodule init
      - git submodule update

  nightly_build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: dessalines/lemmy
      dockerfile: docker/Dockerfile
      platforms: linux/amd64
      build_args: RUST_RELEASE_MODE=release
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # add_host: github.com:140.82.112.3,static.crates.io:18.154.227.73,crates.io:108.138.64.68,dl-cdn.alpinelinux.org:146.75.30.133
      tag: dev
