platform: linux/amd64
depends_on:
  - publish_arm
  - publish_x86

when:
  event: tag

variables:
  - &muslrust_image "clux/muslrust:1.67.0"

steps:
  prepare_repo:
    image: alpine:3
    commands:
      - apk add git
        #- git fetch --tags
      - git submodule init
      - git submodule update

  publish_release_docker_manifest:
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/lemmy:${CI_COMMIT_TAG}"
      template: "dessalines/lemmy:${CI_COMMIT_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true

  publish_latest_release_docker_manifest:
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/lemmy:latest"
      template: "dessalines/lemmy:${CI_COMMIT_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true

  # using https://github.com/pksunkara/cargo-workspaces
  publish_to_crates_io:
    image: *muslrust_image
    commands:
      - 'echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs"'
      - cargo install cargo-workspaces
      - cp -r migrations crates/db_schema/
      - cargo login "$CARGO_API_TOKEN"
      - cargo workspaces publish --from-git --allow-dirty --no-verify --allow-branch "${CI_COMMIT_TAG}" --yes custom "${CI_COMMIT_TAG}"
    secrets: [cargo_api_token]

  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Lemmy CI build failed: ${CI_BUILD_LINK}' ntfy.sh/lemmy_drone_ci"
    when:
      status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'lemmy:${CI_COMMIT_TAG} deployed' ntfy.sh/lemmy_drone_ci"
