use crate::newtypes::{LocalSiteId, SiteId};
use serde::{Deserialize, Serialize};
use typed_builder::TypedBuilder;

#[cfg(feature = "full")]
use crate::schema::local_site;

#[derive(PartialEq, Eq, Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "full", derive(Queryable, Identifiable))]
#[cfg_attr(feature = "full", diesel(table_name = local_site))]
#[cfg_attr(feature = "full", diesel(belongs_to(crate::source::site::Site)))]
pub struct LocalSite {
  pub id: LocalSiteId,
  pub site_id: SiteId,
  pub site_setup: bool,
  pub enable_downvotes: bool,
  pub open_registration: bool,
  pub enable_nsfw: bool,
  pub community_creation_admin_only: bool,
  pub require_email_verification: bool,
  pub require_application: bool,
  pub application_question: Option<String>,
  pub private_instance: bool,
  pub default_theme: String,
  pub default_post_listing_type: String,
  pub legal_information: Option<String>,
  pub hide_modlog_mod_names: bool,
  pub application_email_admins: bool,
  pub slur_filter_regex: Option<String>,
  pub actor_name_max_length: i32,
  pub rate_limit_message: i32,
  pub rate_limit_message_per_second: i32,
  pub rate_limit_post: i32,
  pub rate_limit_post_per_second: i32,
  pub rate_limit_register: i32,
  pub rate_limit_register_per_second: i32,
  pub rate_limit_image: i32,
  pub rate_limit_image_per_second: i32,
  pub rate_limit_comment: i32,
  pub rate_limit_comment_per_second: i32,
  pub rate_limit_search: i32,
  pub rate_limit_search_per_second: i32,
  pub federation_enabled: bool,
  pub federation_debug: bool,
  pub federation_strict_allowlist: bool,
  pub federation_http_fetch_retry_limit: i32,
  pub federation_worker_count: i32,
  pub email_enabled: bool,
  pub email_smtp_server: Option<String>,
  pub email_smtp_login: Option<String>,
  pub email_smtp_password: Option<String>,
  pub email_smtp_from_address: Option<String>,
  pub email_tls_type: String,
  pub captcha_enabled: bool,
  pub captcha_difficulty: String,
  pub published: chrono::NaiveDateTime,
  pub updated: Option<chrono::NaiveDateTime>,
}

#[derive(Clone, TypedBuilder)]
#[builder(field_defaults(default))]
#[cfg_attr(feature = "full", derive(Insertable))]
#[cfg_attr(feature = "full", diesel(table_name = local_site))]
pub struct LocalSiteInsertForm {
  #[builder(!default)]
  pub site_id: SiteId,
  pub site_setup: Option<bool>,
  pub enable_downvotes: Option<bool>,
  pub open_registration: Option<bool>,
  pub enable_nsfw: Option<bool>,
  pub community_creation_admin_only: Option<bool>,
  pub require_email_verification: Option<bool>,
  pub require_application: Option<bool>,
  pub application_question: Option<String>,
  pub private_instance: Option<bool>,
  pub default_theme: Option<String>,
  pub default_post_listing_type: Option<String>,
  pub legal_information: Option<String>,
  pub hide_modlog_mod_names: Option<bool>,
  pub application_email_admins: Option<bool>,
  pub slur_filter_regex: Option<String>,
  pub actor_name_max_length: Option<i32>,
  pub rate_limit_message: Option<i32>,
  pub rate_limit_message_per_second: Option<i32>,
  pub rate_limit_post: Option<i32>,
  pub rate_limit_post_per_second: Option<i32>,
  pub rate_limit_register: Option<i32>,
  pub rate_limit_register_per_second: Option<i32>,
  pub rate_limit_image: Option<i32>,
  pub rate_limit_image_per_second: Option<i32>,
  pub rate_limit_comment: Option<i32>,
  pub rate_limit_comment_per_second: Option<i32>,
  pub rate_limit_search: Option<i32>,
  pub rate_limit_search_per_second: Option<i32>,
  pub federation_enabled: Option<bool>,
  pub federation_debug: Option<bool>,
  pub federation_strict_allowlist: Option<bool>,
  pub federation_http_fetch_retry_limit: Option<i32>,
  pub federation_worker_count: Option<i32>,
  pub email_enabled: Option<bool>,
  pub email_smtp_server: Option<String>,
  pub email_smtp_login: Option<String>,
  pub email_smtp_password: Option<String>,
  pub email_smtp_from_address: Option<String>,
  pub email_tls_type: Option<String>,
  pub captcha_enabled: Option<bool>,
  pub captcha_difficulty: Option<String>,
}

#[derive(Clone, TypedBuilder)]
#[builder(field_defaults(default))]
#[cfg_attr(feature = "full", derive(AsChangeset))]
#[cfg_attr(feature = "full", diesel(table_name = local_site))]
pub struct LocalSiteUpdateForm {
  pub site_setup: Option<bool>,
  pub enable_downvotes: Option<bool>,
  pub open_registration: Option<bool>,
  pub enable_nsfw: Option<bool>,
  pub community_creation_admin_only: Option<bool>,
  pub require_email_verification: Option<bool>,
  pub require_application: Option<bool>,
  pub application_question: Option<Option<String>>,
  pub private_instance: Option<bool>,
  pub default_theme: Option<String>,
  pub default_post_listing_type: Option<String>,
  pub legal_information: Option<Option<String>>,
  pub hide_modlog_mod_names: Option<bool>,
  pub application_email_admins: Option<bool>,
  pub slur_filter_regex: Option<Option<String>>,
  pub actor_name_max_length: Option<i32>,
  pub rate_limit_message: Option<i32>,
  pub rate_limit_message_per_second: Option<i32>,
  pub rate_limit_post: Option<i32>,
  pub rate_limit_post_per_second: Option<i32>,
  pub rate_limit_register: Option<i32>,
  pub rate_limit_register_per_second: Option<i32>,
  pub rate_limit_image: Option<i32>,
  pub rate_limit_image_per_second: Option<i32>,
  pub rate_limit_comment: Option<i32>,
  pub rate_limit_comment_per_second: Option<i32>,
  pub rate_limit_search: Option<i32>,
  pub rate_limit_search_per_second: Option<i32>,
  pub federation_enabled: Option<bool>,
  pub federation_debug: Option<bool>,
  pub federation_strict_allowlist: Option<bool>,
  pub federation_http_fetch_retry_limit: Option<i32>,
  pub federation_worker_count: Option<i32>,
  pub email_enabled: Option<bool>,
  pub email_smtp_server: Option<Option<String>>,
  pub email_smtp_login: Option<Option<String>>,
  pub email_smtp_password: Option<Option<String>>,
  pub email_smtp_from_address: Option<Option<String>>,
  pub email_tls_type: Option<String>,
  pub captcha_enabled: Option<bool>,
  pub captcha_difficulty: Option<String>,
  pub updated: Option<Option<chrono::NaiveDateTime>>,
}
